-- Convert id and FK columns from TEXT to UUID.
--
-- This migration is intentionally fail-fast: it assumes existing ids are already valid UUID strings.
-- If any value cannot be cast, Postgres will error and the migration will abort.
--
-- Note: UUIDv7 generation is handled by Prisma (`@default(uuid(7))`), not by DB defaults.

-- Drop FKs first so we can change column types.
ALTER TABLE "session" DROP CONSTRAINT IF EXISTS "session_userId_fkey";
ALTER TABLE "account" DROP CONSTRAINT IF EXISTS "account_userId_fkey";
ALTER TABLE "passkey" DROP CONSTRAINT IF EXISTS "passkey_userId_fkey";
ALTER TABLE "member" DROP CONSTRAINT IF EXISTS "member_userId_fkey";
ALTER TABLE "member" DROP CONSTRAINT IF EXISTS "member_organizationId_fkey";
ALTER TABLE "invitation" DROP CONSTRAINT IF EXISTS "invitation_organizationId_fkey";
ALTER TABLE "invitation" DROP CONSTRAINT IF EXISTS "invitation_inviterId_fkey";
ALTER TABLE "utmAttribution" DROP CONSTRAINT IF EXISTS "utmAttribution_userId_fkey";
ALTER TABLE "noticeAcknowledgment" DROP CONSTRAINT IF EXISTS "noticeAcknowledgment_userId_fkey";
ALTER TABLE "noticeAcknowledgment" DROP CONSTRAINT IF EXISTS "noticeAcknowledgment_noticeId_fkey";
ALTER TABLE "UnitValue" DROP CONSTRAINT IF EXISTS "UnitValue_agentFixedPricingId_fkey";
ALTER TABLE "AgentPricing" DROP CONSTRAINT IF EXISTS "AgentPricing_agentFixedPricingId_fkey";
ALTER TABLE "ExampleOutput" DROP CONSTRAINT IF EXISTS "ExampleOutput_agentId_fkey";
ALTER TABLE "ExampleOutput" DROP CONSTRAINT IF EXISTS "ExampleOutput_agentIdOverride_fkey";
ALTER TABLE "UserAgentRating" DROP CONSTRAINT IF EXISTS "UserAgentRating_userId_fkey";
ALTER TABLE "UserAgentRating" DROP CONSTRAINT IF EXISTS "UserAgentRating_agentId_fkey";
ALTER TABLE "Agent" DROP CONSTRAINT IF EXISTS "Agent_pricingId_fkey";
ALTER TABLE "AgentList" DROP CONSTRAINT IF EXISTS "AgentList_userId_fkey";
ALTER TABLE "Transaction" DROP CONSTRAINT IF EXISTS "Transaction_userId_fkey";
ALTER TABLE "Transaction" DROP CONSTRAINT IF EXISTS "Transaction_organizationId_fkey";
ALTER TABLE "credit_bucket" DROP CONSTRAINT IF EXISTS "credit_bucket_sourceTransactionId_fkey";
ALTER TABLE "credit_bucket" DROP CONSTRAINT IF EXISTS "credit_bucket_userId_fkey";
ALTER TABLE "credit_bucket" DROP CONSTRAINT IF EXISTS "credit_bucket_organizationId_fkey";
ALTER TABLE "credit_consumption" DROP CONSTRAINT IF EXISTS "credit_consumption_bucketId_fkey";
ALTER TABLE "credit_consumption" DROP CONSTRAINT IF EXISTS "credit_consumption_transactionId_fkey";
ALTER TABLE "Job" DROP CONSTRAINT IF EXISTS "Job_userId_fkey";
ALTER TABLE "Job" DROP CONSTRAINT IF EXISTS "Job_organizationId_fkey";
ALTER TABLE "Job" DROP CONSTRAINT IF EXISTS "Job_agentId_fkey";
ALTER TABLE "Job" DROP CONSTRAINT IF EXISTS "Job_jobScheduleId_fkey";
ALTER TABLE "Job" DROP CONSTRAINT IF EXISTS "Job_taskId_fkey";
ALTER TABLE "jobPurchase" DROP CONSTRAINT IF EXISTS "jobPurchase_jobId_fkey";
ALTER TABLE "jobEvent" DROP CONSTRAINT IF EXISTS "jobEvent_jobId_fkey";
ALTER TABLE "jobInput" DROP CONSTRAINT IF EXISTS "jobInput_eventId_fkey";
ALTER TABLE "blob" DROP CONSTRAINT IF EXISTS "blob_eventId_fkey";
ALTER TABLE "link" DROP CONSTRAINT IF EXISTS "link_eventId_fkey";
ALTER TABLE "jobShare" DROP CONSTRAINT IF EXISTS "jobShare_jobId_fkey";
ALTER TABLE "jobShare" DROP CONSTRAINT IF EXISTS "jobShare_taskId_fkey";
ALTER TABLE "jobSchedule" DROP CONSTRAINT IF EXISTS "jobSchedule_userId_fkey";
ALTER TABLE "jobSchedule" DROP CONSTRAINT IF EXISTS "jobSchedule_organizationId_fkey";
ALTER TABLE "jobSchedule" DROP CONSTRAINT IF EXISTS "jobSchedule_agentId_fkey";
ALTER TABLE "oauthClient" DROP CONSTRAINT IF EXISTS "oauthClient_userId_fkey";
ALTER TABLE "oauthAccessToken" DROP CONSTRAINT IF EXISTS "oauthAccessToken_sessionId_fkey";
ALTER TABLE "oauthAccessToken" DROP CONSTRAINT IF EXISTS "oauthAccessToken_refreshId_fkey";
ALTER TABLE "oauthAccessToken" DROP CONSTRAINT IF EXISTS "oauthAccessToken_userId_fkey";
ALTER TABLE "oauthRefreshToken" DROP CONSTRAINT IF EXISTS "oauthRefreshToken_sessionId_fkey";
ALTER TABLE "oauthRefreshToken" DROP CONSTRAINT IF EXISTS "oauthRefreshToken_userId_fkey";
ALTER TABLE "oauthConsent" DROP CONSTRAINT IF EXISTS "oauthConsent_userId_fkey";
ALTER TABLE "coworker" DROP CONSTRAINT IF EXISTS "coworker_userId_fkey";
ALTER TABLE "coworker_api_key" DROP CONSTRAINT IF EXISTS "coworker_api_key_coworkerId_fkey";
ALTER TABLE "task" DROP CONSTRAINT IF EXISTS "task_userId_fkey";
ALTER TABLE "task" DROP CONSTRAINT IF EXISTS "task_organizationId_fkey";
ALTER TABLE "task" DROP CONSTRAINT IF EXISTS "task_coworkerId_fkey";
ALTER TABLE "task_link" DROP CONSTRAINT IF EXISTS "task_link_fromTaskId_fkey";
ALTER TABLE "task_link" DROP CONSTRAINT IF EXISTS "task_link_toTaskId_fkey";
ALTER TABLE "taskEvent" DROP CONSTRAINT IF EXISTS "taskEvent_taskId_fkey";
ALTER TABLE "taskEvent" DROP CONSTRAINT IF EXISTS "taskEvent_userId_fkey";
ALTER TABLE "taskEvent" DROP CONSTRAINT IF EXISTS "taskEvent_coworkerId_fkey";
ALTER TABLE "taskEvent" DROP CONSTRAINT IF EXISTS "taskEvent_transactionId_fkey";
ALTER TABLE "coworker_usage" DROP CONSTRAINT IF EXISTS "coworker_usage_coworkerId_fkey";
ALTER TABLE "coworker_usage" DROP CONSTRAINT IF EXISTS "coworker_usage_userId_fkey";
ALTER TABLE "coworker_usage" DROP CONSTRAINT IF EXISTS "coworker_usage_organizationId_fkey";
ALTER TABLE "coworker_usage" DROP CONSTRAINT IF EXISTS "coworker_usage_transactionId_fkey";
ALTER TABLE "conversation" DROP CONSTRAINT IF EXISTS "conversation_userId_fkey";
ALTER TABLE "conversationItem" DROP CONSTRAINT IF EXISTS "conversationItem_conversationId_fkey";
ALTER TABLE "_AgentToAgentList" DROP CONSTRAINT IF EXISTS "_AgentToAgentList_A_fkey";
ALTER TABLE "_AgentToAgentList" DROP CONSTRAINT IF EXISTS "_AgentToAgentList_B_fkey";
ALTER TABLE "_AgentTag" DROP CONSTRAINT IF EXISTS "_AgentTag_A_fkey";
ALTER TABLE "_AgentTag" DROP CONSTRAINT IF EXISTS "_AgentTag_B_fkey";
ALTER TABLE "_AgentTagOverride" DROP CONSTRAINT IF EXISTS "_AgentTagOverride_A_fkey";
ALTER TABLE "_AgentTagOverride" DROP CONSTRAINT IF EXISTS "_AgentTagOverride_B_fkey";
ALTER TABLE "_AgentCategory" DROP CONSTRAINT IF EXISTS "_AgentCategory_A_fkey";
ALTER TABLE "_AgentCategory" DROP CONSTRAINT IF EXISTS "_AgentCategory_B_fkey";

-- Alter PKs and FK columns.
ALTER TABLE "user" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "session" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "session" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "account" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "account" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "verification" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "passkey" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "passkey" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "subscription" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "organization" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "member" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "member" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "member" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "invitation" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "invitation" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "invitation" ALTER COLUMN "inviterId" TYPE UUID USING "inviterId"::uuid;
ALTER TABLE "utmAttribution" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "utmAttribution" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "notice" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "noticeAcknowledgment" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "noticeAcknowledgment" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "noticeAcknowledgment" ALTER COLUMN "noticeId" TYPE UUID USING "noticeId"::uuid;
ALTER TABLE "rateLimit" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "UnitValue" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "UnitValue" ALTER COLUMN "agentFixedPricingId" TYPE UUID USING "agentFixedPricingId"::uuid;
ALTER TABLE "AgentPricing" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "AgentPricing" ALTER COLUMN "agentFixedPricingId" TYPE UUID USING "agentFixedPricingId"::uuid;
ALTER TABLE "AgentFixedPricing" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "ExampleOutput" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "ExampleOutput" ALTER COLUMN "agentId" TYPE UUID USING "agentId"::uuid;
ALTER TABLE "ExampleOutput" ALTER COLUMN "agentIdOverride" TYPE UUID USING "agentIdOverride"::uuid;
ALTER TABLE "UserAgentRating" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "UserAgentRating" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "UserAgentRating" ALTER COLUMN "agentId" TYPE UUID USING "agentId"::uuid;
ALTER TABLE "Agent" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "Agent" ALTER COLUMN "pricingId" TYPE UUID USING "pricingId"::uuid;
ALTER TABLE "Category" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "Lock" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "Tag" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "sync_metadata" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "AgentList" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "AgentList" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "Transaction" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "Transaction" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "credit_bucket" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "credit_bucket" ALTER COLUMN "sourceTransactionId" TYPE UUID USING "sourceTransactionId"::uuid;
ALTER TABLE "credit_bucket" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "credit_bucket" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "credit_consumption" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "credit_consumption" ALTER COLUMN "bucketId" TYPE UUID USING "bucketId"::uuid;
ALTER TABLE "credit_consumption" ALTER COLUMN "transactionId" TYPE UUID USING "transactionId"::uuid;
ALTER TABLE "Job" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "Job" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "Job" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "Job" ALTER COLUMN "agentId" TYPE UUID USING "agentId"::uuid;
ALTER TABLE "Job" ALTER COLUMN "jobScheduleId" TYPE UUID USING "jobScheduleId"::uuid;
ALTER TABLE "Job" ALTER COLUMN "taskId" TYPE UUID USING "taskId"::uuid;
ALTER TABLE "jobPurchase" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "jobPurchase" ALTER COLUMN "jobId" TYPE UUID USING "jobId"::uuid;
ALTER TABLE "jobEvent" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "jobEvent" ALTER COLUMN "jobId" TYPE UUID USING "jobId"::uuid;
ALTER TABLE "jobInput" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "jobInput" ALTER COLUMN "eventId" TYPE UUID USING "eventId"::uuid;
ALTER TABLE "CreditCost" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "apikey" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "blob" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "blob" ALTER COLUMN "eventId" TYPE UUID USING "eventId"::uuid;
ALTER TABLE "link" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "link" ALTER COLUMN "eventId" TYPE UUID USING "eventId"::uuid;
ALTER TABLE "jobShare" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "jobShare" ALTER COLUMN "jobId" TYPE UUID USING "jobId"::uuid;
ALTER TABLE "jobShare" ALTER COLUMN "taskId" TYPE UUID USING "taskId"::uuid;
ALTER TABLE "jobSchedule" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "jobSchedule" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "jobSchedule" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "jobSchedule" ALTER COLUMN "agentId" TYPE UUID USING "agentId"::uuid;
ALTER TABLE "oauthClient" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "oauthClient" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "oauthAccessToken" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "oauthAccessToken" ALTER COLUMN "sessionId" TYPE UUID USING "sessionId"::uuid;
ALTER TABLE "oauthAccessToken" ALTER COLUMN "refreshId" TYPE UUID USING "refreshId"::uuid;
ALTER TABLE "oauthAccessToken" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "oauthRefreshToken" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "oauthRefreshToken" ALTER COLUMN "sessionId" TYPE UUID USING "sessionId"::uuid;
ALTER TABLE "oauthRefreshToken" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "oauthConsent" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "oauthConsent" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "jwks" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "coworker" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "coworker" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "coworker_api_key" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "coworker_api_key" ALTER COLUMN "coworkerId" TYPE UUID USING "coworkerId"::uuid;
ALTER TABLE "task" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "task" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "task" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "task" ALTER COLUMN "coworkerId" TYPE UUID USING "coworkerId"::uuid;
ALTER TABLE "task_link" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "task_link" ALTER COLUMN "fromTaskId" TYPE UUID USING "fromTaskId"::uuid;
ALTER TABLE "task_link" ALTER COLUMN "toTaskId" TYPE UUID USING "toTaskId"::uuid;
ALTER TABLE "taskEvent" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "taskEvent" ALTER COLUMN "taskId" TYPE UUID USING "taskId"::uuid;
ALTER TABLE "taskEvent" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "taskEvent" ALTER COLUMN "coworkerId" TYPE UUID USING "coworkerId"::uuid;
ALTER TABLE "taskEvent" ALTER COLUMN "transactionId" TYPE UUID USING "transactionId"::uuid;
ALTER TABLE "coworker_usage" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "coworker_usage" ALTER COLUMN "coworkerId" TYPE UUID USING "coworkerId"::uuid;
ALTER TABLE "coworker_usage" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "coworker_usage" ALTER COLUMN "organizationId" TYPE UUID USING "organizationId"::uuid;
ALTER TABLE "coworker_usage" ALTER COLUMN "transactionId" TYPE UUID USING "transactionId"::uuid;
ALTER TABLE "conversation" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "conversation" ALTER COLUMN "userId" TYPE UUID USING "userId"::uuid;
ALTER TABLE "conversationItem" ALTER COLUMN "id" TYPE UUID USING "id"::uuid;
ALTER TABLE "conversationItem" ALTER COLUMN "conversationId" TYPE UUID USING "conversationId"::uuid;
ALTER TABLE "_AgentToAgentList" ALTER COLUMN "A" TYPE UUID USING "A"::uuid;
ALTER TABLE "_AgentToAgentList" ALTER COLUMN "B" TYPE UUID USING "B"::uuid;
ALTER TABLE "_AgentTag" ALTER COLUMN "A" TYPE UUID USING "A"::uuid;
ALTER TABLE "_AgentTag" ALTER COLUMN "B" TYPE UUID USING "B"::uuid;
ALTER TABLE "_AgentTagOverride" ALTER COLUMN "A" TYPE UUID USING "A"::uuid;
ALTER TABLE "_AgentTagOverride" ALTER COLUMN "B" TYPE UUID USING "B"::uuid;
ALTER TABLE "_AgentCategory" ALTER COLUMN "A" TYPE UUID USING "A"::uuid;
ALTER TABLE "_AgentCategory" ALTER COLUMN "B" TYPE UUID USING "B"::uuid;

-- Recreate FKs.
ALTER TABLE "session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "passkey" ADD CONSTRAINT "passkey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "member" ADD CONSTRAINT "member_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "member" ADD CONSTRAINT "member_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_inviterId_fkey" FOREIGN KEY ("inviterId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "utmAttribution" ADD CONSTRAINT "utmAttribution_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "noticeAcknowledgment" ADD CONSTRAINT "noticeAcknowledgment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "noticeAcknowledgment" ADD CONSTRAINT "noticeAcknowledgment_noticeId_fkey" FOREIGN KEY ("noticeId") REFERENCES "notice"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UnitValue" ADD CONSTRAINT "UnitValue_agentFixedPricingId_fkey" FOREIGN KEY ("agentFixedPricingId") REFERENCES "AgentFixedPricing"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AgentPricing" ADD CONSTRAINT "AgentPricing_agentFixedPricingId_fkey" FOREIGN KEY ("agentFixedPricingId") REFERENCES "AgentFixedPricing"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ExampleOutput" ADD CONSTRAINT "ExampleOutput_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ExampleOutput" ADD CONSTRAINT "ExampleOutput_agentIdOverride_fkey" FOREIGN KEY ("agentIdOverride") REFERENCES "Agent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UserAgentRating" ADD CONSTRAINT "UserAgentRating_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserAgentRating" ADD CONSTRAINT "UserAgentRating_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Agent" ADD CONSTRAINT "Agent_pricingId_fkey" FOREIGN KEY ("pricingId") REFERENCES "AgentPricing"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AgentList" ADD CONSTRAINT "AgentList_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "credit_bucket" ADD CONSTRAINT "credit_bucket_sourceTransactionId_fkey" FOREIGN KEY ("sourceTransactionId") REFERENCES "Transaction"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "credit_bucket" ADD CONSTRAINT "credit_bucket_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "credit_bucket" ADD CONSTRAINT "credit_bucket_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "credit_consumption" ADD CONSTRAINT "credit_consumption_bucketId_fkey" FOREIGN KEY ("bucketId") REFERENCES "credit_bucket"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "credit_consumption" ADD CONSTRAINT "credit_consumption_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_jobScheduleId_fkey" FOREIGN KEY ("jobScheduleId") REFERENCES "jobSchedule"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "task"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "jobPurchase" ADD CONSTRAINT "jobPurchase_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobEvent" ADD CONSTRAINT "jobEvent_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobInput" ADD CONSTRAINT "jobInput_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "jobEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "blob" ADD CONSTRAINT "blob_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "jobEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "link" ADD CONSTRAINT "link_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "jobEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobShare" ADD CONSTRAINT "jobShare_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobShare" ADD CONSTRAINT "jobShare_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobSchedule" ADD CONSTRAINT "jobSchedule_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "jobSchedule" ADD CONSTRAINT "jobSchedule_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "jobSchedule" ADD CONSTRAINT "jobSchedule_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "oauthClient" ADD CONSTRAINT "oauthClient_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_refreshId_fkey" FOREIGN KEY ("refreshId") REFERENCES "oauthRefreshToken"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "oauthAccessToken" ADD CONSTRAINT "oauthAccessToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "oauthRefreshToken" ADD CONSTRAINT "oauthRefreshToken_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "oauthRefreshToken" ADD CONSTRAINT "oauthRefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "oauthConsent" ADD CONSTRAINT "oauthConsent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "coworker" ADD CONSTRAINT "coworker_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "coworker_api_key" ADD CONSTRAINT "coworker_api_key_coworkerId_fkey" FOREIGN KEY ("coworkerId") REFERENCES "coworker"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "task" ADD CONSTRAINT "task_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "task" ADD CONSTRAINT "task_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "task" ADD CONSTRAINT "task_coworkerId_fkey" FOREIGN KEY ("coworkerId") REFERENCES "coworker"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "task_link" ADD CONSTRAINT "task_link_fromTaskId_fkey" FOREIGN KEY ("fromTaskId") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "task_link" ADD CONSTRAINT "task_link_toTaskId_fkey" FOREIGN KEY ("toTaskId") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "taskEvent" ADD CONSTRAINT "taskEvent_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "taskEvent" ADD CONSTRAINT "taskEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "taskEvent" ADD CONSTRAINT "taskEvent_coworkerId_fkey" FOREIGN KEY ("coworkerId") REFERENCES "coworker"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "taskEvent" ADD CONSTRAINT "taskEvent_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "coworker_usage" ADD CONSTRAINT "coworker_usage_coworkerId_fkey" FOREIGN KEY ("coworkerId") REFERENCES "coworker"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "coworker_usage" ADD CONSTRAINT "coworker_usage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "coworker_usage" ADD CONSTRAINT "coworker_usage_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "coworker_usage" ADD CONSTRAINT "coworker_usage_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversation" ADD CONSTRAINT "conversation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversationItem" ADD CONSTRAINT "conversationItem_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

