import { OpenAPIHonoWithAuth } from "@/lib/hono";
import { agentUserRouteAllowlistMiddleware } from "../user-coworker-route-allowlist.js";
import {
  type UserRouteVariables,
  usersPathUserContextMiddleware,
} from "../user-route-context.js";
import mountGetUserBillingDetails from "./billing-details/get.js";
import mountApproveUserCoworkerAccess from "./coworker-access/[accessId]/approve/post.js";
import mountDenyUserCoworkerAccess from "./coworker-access/[accessId]/deny/post.js";
import mountRevokeUserCoworkerAccess from "./coworker-access/[accessId]/revoke/post.js";
import mountGetUserCoworkerAccess from "./coworker-access/get.js";
import mountGetUserCredits from "./credits/get.js";
import mountGetUserDeletion from "./deletion/get.js";
import mountGetUserDesignMd from "./design-md/get.js";
import mountPutUserDesignMd from "./design-md/put.js";
import mountGetUserFiles from "./files/get.js";
import mountPostUserFiles from "./files/post.js";
import mountGetUserById from "./get.js";
import mountGetUserMembers from "./members/get.js";
import mountPostUserNoticeAcknowledge from "./notices/[noticeId]/acknowledge/post.js";
import mountGetUserPendingNotices from "./notices/pending/get.js";
import mountDeleteUserOauthConsent from "./oauth-consents/[consentId]/delete.js";
import mountGetUserOrganizationCredits from "./organizations/[organizationId]/credits/get.js";
import mountGetUserOrganizationMember from "./organizations/[organizationId]/member/get.js";
import mountGetUserOrganizations from "./organizations/get.js";
import mountGetUserPendingOrganizationInvitations from "./pending-organization-invitations/get.js";
import mountDeleteUserPersonalWorkspace from "./personal-workspace/delete.js";
import mountPostUserPersonalWorkspace from "./personal-workspace/post.js";
import mountGetUserPreferences from "./preferences/get.js";
import mountPatchUserPreferences from "./preferences/patch.js";
import mountPutUserPreferredOrganization from "./preferred-organization/put.js";
import mountGetUserStripeCustomer from "./stripe-customer/get.js";
import mountPostUserStripeCustomer from "./stripe-customer/post.js";
import mountGetUserSubscription from "./subscription/get.js";
import mountPostUserUtmAttribution from "./utm-attribution/post.js";
import mountApproveUserVendorGrant from "./vendor-grants/[grantId]/approve/post.js";
import mountDenyUserVendorGrant from "./vendor-grants/[grantId]/deny/post.js";
import mountRevokeUserVendorGrant from "./vendor-grants/[grantId]/revoke/post.js";
import mountGetUserVendorGrants from "./vendor-grants/get.js";
import mountPostUserVendorGrants from "./vendor-grants/post.js";
import mountGetUserWorkspaceAccess from "./workspace-access/get.js";

const app = new OpenAPIHonoWithAuth<UserRouteVariables>();

app.use("*", usersPathUserContextMiddleware);
app.use("*", agentUserRouteAllowlistMiddleware);

mountGetUserCredits(app);
mountGetUserDeletion(app);
mountGetUserDesignMd(app);
mountPutUserDesignMd(app);
mountGetUserMembers(app);
mountGetUserOrganizations(app);
mountGetUserOrganizationCredits(app);
mountGetUserOrganizationMember(app);
mountGetUserPreferences(app);
mountPatchUserPreferences(app);
mountPutUserPreferredOrganization(app);
mountPostUserPersonalWorkspace(app);
mountDeleteUserPersonalWorkspace(app);
mountDeleteUserOauthConsent(app);
mountGetUserWorkspaceAccess(app);
mountGetUserPendingOrganizationInvitations(app);
mountGetUserPendingNotices(app);
mountPostUserNoticeAcknowledge(app);
mountGetUserFiles(app);
mountPostUserFiles(app);
mountPostUserUtmAttribution(app);
mountGetUserCoworkerAccess(app);
mountApproveUserCoworkerAccess(app);
mountDenyUserCoworkerAccess(app);
mountRevokeUserCoworkerAccess(app);
mountGetUserVendorGrants(app);
mountPostUserVendorGrants(app);
mountApproveUserVendorGrant(app);
mountDenyUserVendorGrant(app);
mountRevokeUserVendorGrant(app);
mountGetUserStripeCustomer(app);
mountPostUserStripeCustomer(app);
mountGetUserBillingDetails(app);
mountGetUserSubscription(app);
mountGetUserById(app);

export default app;
