export enum OrganizationActionErrorCode {
  // common
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_MEMBER = "NOT_MEMBER",
  NOT_ADMIN = "NOT_ADMIN",
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
  MEMBER_NOT_IN_ORGANIZATION = "MEMBER_NOT_IN_ORGANIZATION",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  // when leave organization
  MEMBER_COUNT_NOT_ALLOWED = "MEMBER_COUNT_NOT_ALLOWED",

  // when change member role
  CHANGE_MY_ROLE_NOT_ALLOWED = "CHANGE_MY_ROLE_NOT_ALLOWED",

  // when kick member
  KICK_MYSELF_NOT_ALLOWED = "KICK_MYSELF_NOT_ALLOWED",
}
