export enum LeaveOrganizationErrorCodes {
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  MEMBER_COUNT_NOT_ALLOWED = "MEMBER_COUNT_NOT_ALLOWED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export enum UpdateOrganizationInformationErrorCodes {
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  NOT_MEMBER = "NOT_MEMBER",
  NOT_ADMIN = "NOT_ADMIN",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
