export enum AuthErrorCode {
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_CREATE_FAILED = "ORGANIZATION_CREATE_FAILED",
  EMAIL_DOMAIN_INVALID = "EMAIL_DOMAIN_INVALID",
  EMAIL_NOT_ALLOWED_BY_ORGANIZATION = "EMAIL_NOT_ALLOWED_BY_ORGANIZATION",
  INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND",
  MEMBER_CREATE_FAILED = "MEMBER_CREATE_FAILED",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  TERMS_NOT_ACCEPTED = "TERMS_NOT_ACCEPTED",
}
