export enum BillingErrorCode {
  PROMOTION_CODE_NOT_FOUND = "PROMOTION_CODE_NOT_FOUND",
  CLAIM_FREE_CREDITS_ERROR = "CLAIM_FREE_CREDITS_ERROR",
  GET_FREE_CREDITS_WITH_COUPON_ERROR = "GET_FREE_CREDITS_WITH_COUPON_ERROR",
  PURCHASE_CREDITS_ERROR = "PURCHASE_CREDITS_ERROR",
  INVALID_COUPON = "INVALID_COUPON",
  COUPON_NOT_FOUND = "COUPON_NOT_FOUND",
  COUPON_TYPE_ERROR = "COUPON_TYPE_ERROR",
  COUPON_CURRENCY_ERROR = "COUPON_CURRENCY_ERROR",
  INVALID_CREDITS = "INVALID_CREDITS",
}
