export enum JobErrorCode {
  JOB_NOT_FOUND = "JOB_NOT_FOUND",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  AGENT_NOT_FOUND = "AGENT_NOT_FOUND",
  AGENT_UNAVAILABLE = "AGENT_UNAVAILABLE",
  AGENT_PRICING_NOT_FOUND = "AGENT_PRICING_NOT_FOUND",
  COST_TOO_HIGH = "COST_TOO_HIGH",
  PRICING_SCHEMA_MISMATCH = "PRICING_SCHEMA_MISMATCH",
  INPUT_HASH_MISMATCH = "INPUT_HASH_MISMATCH",
  AGENT_JOB_START_FAILED = "AGENT_JOB_START_FAILED",
  PURCHASE_CREATION_FAILED = "PURCHASE_CREATION_FAILED",
  JOB_NAME_GENERATION_FAILED = "JOB_NAME_GENERATION_FAILED",
}
