# linear cli
# https://github.com/schpet/linear-cli

workspace = "masumi"
team_id = "SOK"
issue_sort = "priority"
vcs = "git"

# Currently not used by the CLI, but we can use it to filter issues by project.
# project_id = "sokosumi-6357694ddd23"
