export enum BillingErrorCode {
  PROMOTION_CODE_NOT_FOUND = "PROMOTION_CODE_NOT_FOUND",
  INVALID_COUPON = "INVALID_COUPON",
  COUPON_NOT_FOUND = "COUPON_NOT_FOUND",
  COUPON_TYPE_ERROR = "COUPON_TYPE_ERROR",
  COUPON_CURRENCY_ERROR = "COUPON_CURRENCY_ERROR",
  INVALID_CREDITS = "INVALID_CREDITS",
}
