#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO="masumi-network/sokosumi"
ORG="masumi-network"
SPARKLE_VERSION="2.10.0"
# A named keychain account, so this key never collides with another app's
# Sparkle key on the same Mac (generate_keys defaults to one shared account).
KEY_ACCOUNT="sokosumi-macos"
ITEM_TITLE="Sokosumi macOS Sparkle EdDSA key"

# Private keys pass through this directory only; it is removed on exit.
umask 077
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

banner "Sokosumi macOS releases: updates and Release PR"

# Release secrets are never written to .env: they belong in GitHub secrets
# and 1Password, nowhere else on disk.

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Sparkle's key tool"
say "Sparkle signs every update with an EdDSA key. Its own generate_keys tool"
say "creates the pair; this stage fetches Sparkle $SPARKLE_VERSION's tools into a temp folder."
printf '\n'

if ! curl -fsSL -o "$WORK/sparkle.tar.xz" \
  "https://github.com/sparkle-project/Sparkle/releases/download/$SPARKLE_VERSION/Sparkle-$SPARKLE_VERSION.tar.xz"; then
  warn "Download failed. Check the network and re-run."
  exit 1
fi
mkdir -p "$WORK/sparkle"
tar -xJf "$WORK/sparkle.tar.xz" -C "$WORK/sparkle" ./bin/generate_keys 2>/dev/null \
  || tar -xJf "$WORK/sparkle.tar.xz" -C "$WORK/sparkle" bin/generate_keys
GENERATE_KEYS="$WORK/sparkle/bin/generate_keys"
[[ -x "$GENERATE_KEYS" ]] || { warn "generate_keys missing from the archive."; exit 1; }
printf '  %s✓%s generate_keys ready.\n' "$GREEN" "$RESET"
pause "Press Enter to continue."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Sparkle EdDSA key pair"
say "Every shipped app trusts exactly one public key. Lose the private key and"
say "no installed app can accept another update, so there is only ever one pair."
printf '\n'

if PUBLIC_KEY="$("$GENERATE_KEYS" --account "$KEY_ACCOUNT" -p 2>/dev/null)" && [[ -n "$PUBLIC_KEY" ]]; then
  printf '  %s✓%s This Mac already holds the key (keychain account %s).\n' "$GREEN" "$RESET" "$KEY_ACCOUNT"
else
  warn "No key in this Mac's keychain under account $KEY_ACCOUNT."
  warn "If anyone already generated it (look for '$ITEM_TITLE' in 1Password),"
  warn "stop now: a second pair would not match apps already shipped."
  printf '\n'
  confirm "Create the key pair now?" || { say "Stopping. Nothing changed."; exit 1; }
  note "macOS may ask to let generate_keys use the keychain. Allow it."
  "$GENERATE_KEYS" --account "$KEY_ACCOUNT" >/dev/null
  PUBLIC_KEY="$("$GENERATE_KEYS" --account "$KEY_ACCOUNT" -p)"
fi

"$GENERATE_KEYS" --account "$KEY_ACCOUNT" -x "$WORK/sparkle_private.key" >/dev/null
SPARKLE_PRIVATE_KEY="$(tr -d '\n' < "$WORK/sparkle_private.key")"
[[ -n "$SPARKLE_PRIVATE_KEY" ]] || { warn "Export produced an empty key."; exit 1; }

printf '\n'
say "Public key (goes into the app's Info.plist as SUPublicEDKey):"
printf '\n    %s%s%s\n\n' "$BOLD" "$PUBLIC_KEY" "$RESET"
set_secret SPARKLE_ED_PRIVATE_KEY "$SPARKLE_PRIVATE_KEY"
set_var SPARKLE_ED_PUBLIC_KEY "$PUBLIC_KEY"
pause "Press Enter to continue."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Back the private key up in 1Password"
say "The GitHub secret cannot be read back. 1Password is the copy you restore from."
printf '\n'

backed_up=false
if command -v op >/dev/null 2>&1 && op vault list >/dev/null 2>&1; then
  say "Your vaults:"
  op vault list --format=json | grep -o '"name": *"[^"]*"' | sed 's/"name": *"\(.*\)"/    \1/'
  printf '\n'
  VAULT=""
  while [[ -z "$VAULT" ]]; do ask VAULT "Vault shared with the masumi team:"; done

  if op item get "$ITEM_TITLE" --vault "$VAULT" >/dev/null 2>&1; then
    printf '  %s✓%s "%s" already exists in %s. Left as it is.\n' "$GREEN" "$RESET" "$ITEM_TITLE" "$VAULT"
    backed_up=true
  else
    # A template file, not field=value arguments, so the key never shows up in
    # the process list.
    printf '{"title":"%s","category":"PASSWORD","fields":[{"id":"password","type":"CONCEALED","purpose":"PASSWORD","label":"password","value":"%s"},{"id":"notesPlain","type":"STRING","purpose":"NOTES","label":"notesPlain","value":"Sparkle EdDSA private key for the Sokosumi Mac app (%s). Public key: %s. GitHub secret: SPARKLE_ED_PRIVATE_KEY. Restore with: generate_keys --account %s -f <file>. ADR 0053."}]}' \
      "$ITEM_TITLE" "$SPARKLE_PRIVATE_KEY" "$REPO" "$PUBLIC_KEY" "$KEY_ACCOUNT" > "$WORK/item.json"
    if op item create --vault "$VAULT" --template "$WORK/item.json" >/dev/null 2>&1 \
       && op item get "$ITEM_TITLE" --vault "$VAULT" >/dev/null 2>&1; then
      printf '  %s✓%s Saved "%s" in %s.\n' "$GREEN" "$RESET" "$ITEM_TITLE" "$VAULT"
      backed_up=true
    else
      warn "1Password refused the item."
    fi
    rm -f "$WORK/item.json"
  fi
fi

if [[ "$backed_up" != true ]]; then
  say "Save it by hand instead:"
  step "In 1Password, create a Password item named '$ITEM_TITLE' in the shared masumi vault."
  step "Paste the clipboard into the password field and save."
  printf '%s' "$SPARKLE_PRIVATE_KEY" | pbcopy
  note "The private key is on the clipboard now."
  pause "Press Enter once the item is saved."
  printf '' | pbcopy
  note "Clipboard cleared."
  confirm "Is the item saved in 1Password?" || SKIPPED+=("1Password backup of the Sparkle private key")
fi
pause "Press Enter to continue."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Create the release GitHub App"
say "Release Please opens the Release PR as this App. A PR opened with the"
say "built-in GITHUB_TOKEN would run no checks and could never merge."
note "Creating an organization App needs the owner or App manager role in $ORG."
printf '\n'
open_url "https://github.com/organizations/$ORG/settings/apps/new"
step "GitHub App name: 'Sokosumi Release' (add a suffix if the name is taken)."
step "Homepage URL: https://github.com/$REPO"
step "Webhook: untick 'Active'."
step "Repository permissions → Contents: Read and write."
step "Repository permissions → Pull requests: Read and write."
step "Leave every other permission at No access (Metadata stays Read-only)."
step "Where can this GitHub App be installed: 'Only on this account'."
step "Click 'Create GitHub App'."
printf '\n'
step "On the App's General page, copy the App ID (a number, not the Client ID)."
printf '\n'

RELEASE_APP_ID=""
while :; do
  ask RELEASE_APP_ID "App ID:"
  [[ "$RELEASE_APP_ID" =~ ^[0-9]+$ ]] && break
  warn "The App ID is digits only. Try again."
done
set_secret RELEASE_APP_ID "$RELEASE_APP_ID"
pause "Press Enter to continue."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "App private key and installation"
step "Still on the App's General page, scroll to 'Private keys'."
step "Click 'Generate a private key'. A .pem file downloads."
printf '\n'

PEM_PATH=""
while :; do
  ask PEM_PATH "Path to the downloaded .pem:"
  PEM_PATH="${PEM_PATH/#\~/$HOME}"
  PEM_PATH="${PEM_PATH%\"}"; PEM_PATH="${PEM_PATH#\"}"
  [[ -f "$PEM_PATH" ]] && grep -q "PRIVATE KEY" "$PEM_PATH" && break
  warn "No private key at that path. Try again."
done
set_secret RELEASE_APP_PRIVATE_KEY "$(cat "$PEM_PATH")"
printf '\n'
step "In the App's left sidebar, click 'Install App', then Install next to $ORG."
step "Choose 'Only select repositories', pick 'sokosumi', then Install."
printf '\n'
pause "Press Enter once the App is installed."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Verify"
say "Signing in as the App and asking GitHub whether it is installed on $REPO."
printf '\n'

now="$(date +%s)"
header="$(printf '{"alg":"RS256","typ":"JWT"}' | b64url)"
payload="$(printf '{"iat":%s,"exp":%s,"iss":"%s"}' "$((now - 60))" "$((now + 540))" "$RELEASE_APP_ID" | b64url)"
signature="$(printf '%s.%s' "$header" "$payload" | openssl dgst -sha256 -sign "$PEM_PATH" -binary | b64url)"
if curl -fsS -o /dev/null \
     -H "Authorization: Bearer $header.$payload.$signature" \
     -H "Accept: application/vnd.github+json" \
     "https://api.github.com/repos/$REPO/installation"; then
  printf '  %s✓%s The App can act on %s.\n' "$GREEN" "$RESET" "$REPO"
else
  warn "GitHub did not confirm the installation. Check the App ID matches the"
  warn ".pem, and that the App is installed on $REPO."
  SKIPPED+=("release App failed the installation check")
fi
printf '\n'

if confirm "Delete the local .pem now that it is in GitHub secrets?"; then
  rm -f "$PEM_PATH" && printf '  %s✓%s Deleted %s\n' "$GREEN" "$RESET" "$PEM_PATH"
else
  warn "Remember to delete $PEM_PATH yourself."
fi
printf '\n'

say "Release secrets and variables now on $REPO:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret list --repo "$REPO" 2>/dev/null \
    | grep -E "^(SPARKLE_ED_PRIVATE_KEY|RELEASE_APP_ID|RELEASE_APP_PRIVATE_KEY)\b" \
    | sed 's/^/    /' || warn "none of the three secrets are set yet"
  gh variable list --repo "$REPO" 2>/dev/null \
    | grep -E "^SPARKLE_ED_PUBLIC_KEY\b" | sed 's/^/    /' || warn "SPARKLE_ED_PUBLIC_KEY is not set yet"
fi
printf '\n'
say "Public key for the app's Info.plist:"
printf '    %s\n\n' "$PUBLIC_KEY"
note "This Mac's keychain keeps a copy under account $KEY_ACCOUNT."
pause "Press Enter to finish."

finish
