#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Sokosumi macOS release signing"

REPO="masumi-network/sokosumi"
TEAM_ID="GVWN7HXYJB"
DEV_ID_PREFIX="Developer ID Application"

# Signing credentials are never written to .env: they belong in GitHub
# secrets and nowhere else on disk. That means re-runs re-prompt rather than
# offering the previous value, which is the right trade for a private key.

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Developer ID Application certificate"
say "Gatekeeper refuses a sandboxed, hardened-runtime app unless it is signed"
say "with a Developer ID Application certificate. Apple Development will not do."
printf '\n'

if security find-identity -v -p codesigning 2>/dev/null | grep -q "$DEV_ID_PREFIX"; then
  printf '  %s✓%s Found one already:\n' "$GREEN" "$RESET"
  security find-identity -v -p codesigning | grep "$DEV_ID_PREFIX" | sed 's/^/    /'
  pause "Press Enter to continue."
else
  warn "No Developer ID Application certificate in your keychain."
  printf '\n'
  say "Creating one needs the Account Holder or Admin role in the Apple"
  say "Developer account for team $TEAM_ID. Xcode does the certificate-signing"
  say "request for you, which is much less painful than the web flow."
  printf '\n'
  step "Open Xcode → Settings → Accounts."
  step "Select your Apple ID, then the team, then click Manage Certificates."
  step "Click + at the bottom left and choose 'Developer ID Application'."
  step "Wait for it to appear in the list, then close Settings."
  printf '\n'
  note "No + option for Developer ID? Your account lacks the role. Ask the"
  note "Account Holder to create it and send you the .p12 from stage 2."
  printf '\n'
  pause "Press Enter once the certificate exists."

  if security find-identity -v -p codesigning 2>/dev/null | grep -q "$DEV_ID_PREFIX"; then
    printf '  %s✓%s Certificate found.\n' "$GREEN" "$RESET"
  else
    warn "Still not visible in your keychain."
    if ! confirm "Continue anyway (you have the .p12 from someone else)?"; then
      say "Stopping here. Re-run this script once the certificate exists."
      exit 1
    fi
  fi
fi

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Export the certificate for CI"
say "CI needs the certificate AND its private key, which is what .p12 carries."
printf '\n'
step "Open Keychain Access (⌘-Space, type 'Keychain Access')."
step "Select the 'login' keychain, then the 'My Certificates' category."
step "Find '$DEV_ID_PREFIX: … ($TEAM_ID)'."
step "Right-click it → Export …, choose Personal Information Exchange (.p12)."
step "Save it somewhere temporary, e.g. ~/Desktop/sokosumi-signing.p12."
step "Set an export password when prompted. Any strong password; you paste it below."
printf '\n'
warn "Export the certificate ROW, not the private key underneath it."
printf '\n'
open_url "https://support.apple.com/guide/keychain-access/kyca35961/mac"
pause "Press Enter once the .p12 is saved."

P12_PATH=""
while :; do
  ask P12_PATH "Path to the exported .p12:"
  P12_PATH="${P12_PATH/#\~/$HOME}"
  P12_PATH="${P12_PATH%\"}"; P12_PATH="${P12_PATH#\"}"
  [[ -f "$P12_PATH" ]] && break
  warn "No file at that path. Try again."
done

ask_secret P12_PASSWORD "The export password you just set:"

if ! security pkcs12 -in "$P12_PATH" -passin "pass:$P12_PASSWORD" -noout 2>/dev/null \
   && ! openssl pkcs12 -in "$P12_PATH" -passin "pass:$P12_PASSWORD" -noout -legacy 2>/dev/null \
   && ! openssl pkcs12 -in "$P12_PATH" -passin "pass:$P12_PASSWORD" -noout 2>/dev/null; then
  warn "Could not open that .p12 with that password. CI would fail the same way."
  confirm "Set the secrets anyway?" || exit 1
fi

set_secret APPLE_DEVELOPER_ID_CERT_P12 "$(base64 < "$P12_PATH" | tr -d '\n')"
set_secret APPLE_DEVELOPER_ID_CERT_PASSWORD "$P12_PASSWORD"
printf '\n'
if confirm "Delete the local .p12 now that it is in GitHub secrets?"; then
  rm -f "$P12_PATH" && printf '  %s✓%s Deleted %s\n' "$GREEN" "$RESET" "$P12_PATH"
else
  warn "Remember to delete $P12_PATH yourself."
fi
pause "Press Enter to continue."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "App Store Connect API key for notarization"
say "notarytool authenticates with an App Store Connect API key rather than"
say "your Apple ID, so the credential is not tied to one person and can be"
say "revoked on its own."
printf '\n'
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Users and Access → Integrations → App Store Connect API → Team Keys."
step "Click + , name it something like 'Sokosumi notarization'."
step "Give it the Developer role, then Generate."
printf '\n'
warn "The .p8 downloads exactly ONCE. Lose it and you generate a new key."
printf '\n'
step "Download the .p8 file."
step "Copy the KEY ID from the key's row."
step "Copy the ISSUER ID shown above the table (same for every key on the team)."
printf '\n'
pause "Press Enter once you have the .p8, the Key ID and the Issuer ID."

P8_PATH=""
while :; do
  ask P8_PATH "Path to the downloaded .p8:"
  P8_PATH="${P8_PATH/#\~/$HOME}"
  P8_PATH="${P8_PATH%\"}"; P8_PATH="${P8_PATH#\"}"
  [[ -f "$P8_PATH" ]] && break
  warn "No file at that path. Try again."
done

ask NOTARY_KEY_ID "Key ID:"
ask NOTARY_ISSUER_ID "Issuer ID:"

set_secret APPLE_NOTARY_KEY_P8 "$(base64 < "$P8_PATH" | tr -d '\n')"
set_secret APPLE_NOTARY_KEY_ID "$NOTARY_KEY_ID"
set_secret APPLE_NOTARY_ISSUER_ID "$NOTARY_ISSUER_ID"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Verify"
say "Asking Apple's notary service for this key's submission history. It"
say "answers only if the key, key ID and issuer ID all line up."
printf '\n'

if xcrun notarytool history --key "$P8_PATH" --key-id "$NOTARY_KEY_ID" \
     --issuer "$NOTARY_ISSUER_ID" >/dev/null 2>&1; then
  printf '  %s✓%s Apple accepted the notarization credentials.\n' "$GREEN" "$RESET"
else
  warn "Apple rejected them. Check the Key ID and Issuer ID are not swapped,"
  warn "and that the .p8 belongs to this team."
  SKIPPED+=("notarization credentials failed a live check")
fi
printf '\n'

if confirm "Delete the local .p8 now that it is in GitHub secrets?"; then
  rm -f "$P8_PATH" && printf '  %s✓%s Deleted %s\n' "$GREEN" "$RESET" "$P8_PATH"
else
  warn "Remember to delete $P8_PATH yourself."
fi
printf '\n'

say "Secrets now on $REPO:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret list --repo "$REPO" 2>/dev/null \
    | grep -E "APPLE_DEVELOPER_ID_CERT_P12|APPLE_DEVELOPER_ID_CERT_PASSWORD|APPLE_NOTARY_KEY_P8|APPLE_NOTARY_KEY_ID|APPLE_NOTARY_ISSUER_ID" \
    | sed 's/^/    /' || warn "none of the five are set yet"
fi
printf '\n'
say "Next: merge an Apple change to main. The 'Publish rolling DMG' job builds,"
say "notarizes and attaches the disk image to the apple-latest prerelease."
pause "Press Enter to finish."

finish
