export enum AuthErrorCode {
  EMAIL_DOMAIN_NOT_ALLOWED = "EMAIL_DOMAIN_NOT_ALLOWED",
  TERMS_NOT_ACCEPTED = "TERMS_NOT_ACCEPTED",
  CREDENTIAL_ACCOUNT_ALREADY_EXISTS = "CREDENTIAL_ACCOUNT_ALREADY_EXISTS",
}
