export enum CommonErrorCode {
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  BAD_INPUT = "BAD_INPUT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
