export enum OrganizationErrorCode {
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  NOT_ORGANIZATION_MEMBER = "NOT_ORGANIZATION_MEMBER",
  ORGANIZATION_ENTERPRISE_CONTRACT_EXCLUSIVE = "ORGANIZATION_ENTERPRISE_CONTRACT_EXCLUSIVE",
}
