export enum WorkspaceGateErrorCode {
  PERSONAL_WORKSPACE_ALREADY_EXISTS = "PERSONAL_WORKSPACE_ALREADY_EXISTS",
  LAST_WORKSPACE = "LAST_WORKSPACE",
  WORKSPACE_HAS_DEPENDENTS = "WORKSPACE_HAS_DEPENDENTS",
}
