import { OpenAPIHonoWithAuth } from "@/lib/hono";

import { mountSokoBotApiKeyRoutes } from "./api-keys.js";
import { mountSokoBotAvatarRoutes } from "./avatars.js";
import { mountSokoBotEventRoutes } from "./events.js";
import { sokoBotRouteGate } from "./helpers.js";
import mountGetIntegrationsCatalog from "./integrations/catalog/get.js";
import mountGetMySokoBotActivity from "./me/activity/get.js";
import mountClaimMySokoBotAvatar from "./me/avatar/post.js";
import mountUpdateMySokoBotBoardFollowing from "./me/board-following/put.js";
import mountResolveMySokoBotDecision from "./me/decisions/[decisionId]/post.js";
import mountArchiveMySokoBot from "./me/delete.js";
import mountGetMySokoBot from "./me/get.js";
import mountConnectMySokoBotIntegration from "./me/integrations/[provider]/connect/post.js";
import mountDisconnectMySokoBotIntegration from "./me/integrations/[provider]/delete.js";
import mountFinalizeMySokoBotIntegration from "./me/integrations/[provider]/finalize/post.js";
import mountGetMySokoBotIntegrations from "./me/integrations/get.js";
import mountIntroduceMySokoBot from "./me/introduce/post.js";
import mountRunMySokoBotLabIngest from "./me/lab/ingest/post.js";
import mountJudgeMySokoBotLabTurn from "./me/lab/judge/post.js";
import mountListMySokoBotLabRuns from "./me/lab/runs/get.js";
import mountSimulateMySokoBotTaskEvent from "./me/lab/task-event/post.js";
import mountResetMySokoBotMemory from "./me/memory/reset/post.js";
import mountDeleteMySokoBotPermanently from "./me/permanent/delete.js";
import mountCreateMySokoBot from "./me/post.js";
import mountUpdateMySokoBotProactive from "./me/proactive/put.js";
import mountDeleteMySokoBotSchedule from "./me/schedules/[scheduleId]/delete.js";
import mountUpdateMySokoBotSchedule from "./me/schedules/[scheduleId]/patch.js";
import mountCreateMySokoBotSchedule from "./me/schedules/post.js";
import mountRemoveMySokoBotSkill from "./me/skills/[skillId]/delete.js";
import mountListMySokoBotSkills from "./me/skills/get.js";
import mountInstallMySokoBotSkill from "./me/skills/post.js";
import mountGetMySokoBotStats from "./me/stats/get.js";
import mountSendMySokoBotTurnFeedback from "./me/turns/[id]/feedback/post.js";
import mountCancelMySokoBotTurn from "./me/turns/[turnId]/cancel/post.js";
import mountGetMySokoBotTurn from "./me/turns/[turnId]/get.js";
import mountListMySokoBotTurns from "./me/turns/get.js";
import mountStartMySokoBotTurn from "./me/turns/post.js";
import mountGetMySokoBotUsage from "./me/usage/get.js";
import mountUpdateMySokoBotVersion from "./me/version/put.js";
import mountBrowseSokoBotSkills from "./skills/browse/get.js";
import mountSearchSokoBotSkills from "./skills/search/get.js";
import mountGetSokoBotTeam from "./team/get.js";
import mountListSokoBotVersions from "./versions/get.js";

const app = new OpenAPIHonoWithAuth({ includeWorkspaceContext: true });

app.use("*", sokoBotRouteGate);

mountSokoBotApiKeyRoutes(app);
mountSokoBotEventRoutes(app);
mountGetMySokoBot(app);
mountGetMySokoBotActivity(app);
mountGetMySokoBotUsage(app);
mountCreateMySokoBot(app);
mountArchiveMySokoBot(app);
mountDeleteMySokoBotPermanently(app);
mountStartMySokoBotTurn(app);
mountListMySokoBotTurns(app);
mountGetMySokoBotTurn(app);
mountCancelMySokoBotTurn(app);
mountResetMySokoBotMemory(app);
mountCreateMySokoBotSchedule(app);
mountUpdateMySokoBotSchedule(app);
mountDeleteMySokoBotSchedule(app);
mountResolveMySokoBotDecision(app);
mountSokoBotAvatarRoutes(app);
mountGetMySokoBotIntegrations(app);
mountGetIntegrationsCatalog(app);
mountConnectMySokoBotIntegration(app);
mountFinalizeMySokoBotIntegration(app);
mountDisconnectMySokoBotIntegration(app);
mountIntroduceMySokoBot(app);
mountClaimMySokoBotAvatar(app);
mountListSokoBotVersions(app);
mountUpdateMySokoBotProactive(app);
mountSendMySokoBotTurnFeedback(app);
mountUpdateMySokoBotBoardFollowing(app);
mountUpdateMySokoBotVersion(app);
mountRunMySokoBotLabIngest(app);
mountSimulateMySokoBotTaskEvent(app);
mountGetSokoBotTeam(app);
mountGetMySokoBotStats(app);
mountListMySokoBotSkills(app);
mountInstallMySokoBotSkill(app);
mountRemoveMySokoBotSkill(app);
mountSearchSokoBotSkills(app);
mountBrowseSokoBotSkills(app);
mountListMySokoBotLabRuns(app);
mountJudgeMySokoBotLabTurn(app);

export default app;
