"use server";

import { revalidatePath } from "next/cache";

import { CoreApiRequestError } from "@/lib/clients/core.client";
import type {
  ProjectImageAsset,
  ProjectImageJob,
  ProjectImageSession,
} from "@/lib/clients/generated/core/types.gen";
import { imageStudioService } from "@/lib/services/image-studio.service";
import {
  type AuthenticatedRequest,
  withSession,
} from "@/middleware/auth-middleware";

/**
 * Mutations for the image studio.
 *
 * Each one is a pass-through to Core, which owns every access check. The only
 * judgement here is turning a Core failure into a message a person can act on.
 */

interface StartGenerationParameters extends AuthenticatedRequest {
  projectId: string;
  prompt: string;
  aspectRatio: string;
  resolution: string;
  parentAssetId: string | null;
  referenceAssetIds: string[];
  sessionId: string | null;
  /**
   * Generated by the client before the first attempt and reused on every
   * retry of the same intent, so a retry returns the original job rather than
   * buying a second image.
   */
  idempotencyKey: string;
}

interface ReviewParameters extends AuthenticatedRequest {
  projectId: string;
  assetId: string;
  decision: "APPROVED" | "REJECTED";
  feedback: string | null;
}

interface ClearReviewParameters extends AuthenticatedRequest {
  projectId: string;
  assetId: string;
}

interface CancelParameters extends AuthenticatedRequest {
  projectId: string;
  jobId: string;
}

interface BindSessionParameters extends AuthenticatedRequest {
  projectId: string;
  eveSessionId: string;
  title: string | null;
}

function rethrow(error: unknown, fallback: string): never {
  if (error instanceof CoreApiRequestError) {
    throw new Error(error.message || fallback);
  }
  throw error instanceof Error ? error : new Error(fallback);
}

export const startImageGeneration = withSession<
  StartGenerationParameters,
  ProjectImageJob
>(async (input) => {
  try {
    const job = await imageStudioService.createJob(input.projectId, {
      prompt: input.prompt,
      settings: {
        aspectRatio: input.aspectRatio as never,
        resolution: input.resolution as never,
        outputFormat: "png",
        seed: null,
      },
      referenceAssetIds: input.referenceAssetIds,
      parentAssetId: input.parentAssetId,
      sessionId: input.sessionId,
      idempotencyKey: input.idempotencyKey,
    });
    revalidatePath(`/projects/${input.projectId}/studio`);
    return job;
  } catch (error) {
    rethrow(error, "Could not start the image generation.");
  }
});

export const reviewImageVersion = withSession<
  ReviewParameters,
  ProjectImageAsset
>(async ({ projectId, assetId, decision, feedback }) => {
  try {
    const asset = await imageStudioService.reviewAsset(projectId, assetId, {
      decision,
      feedback,
    });
    revalidatePath(`/projects/${projectId}/studio`);
    return asset;
  } catch (error) {
    rethrow(error, "Could not record the review.");
  }
});

export const clearImageVersionReview = withSession<
  ClearReviewParameters,
  ProjectImageAsset
>(async ({ projectId, assetId }) => {
  try {
    const asset = await imageStudioService.clearAssetReview(projectId, assetId);
    revalidatePath(`/projects/${projectId}/studio`);
    return asset;
  } catch (error) {
    rethrow(error, "Could not clear the review.");
  }
});

export const requestImageJobCancel = withSession<
  CancelParameters,
  { accepted: boolean }
>(async ({ projectId, jobId }) => {
  try {
    return await imageStudioService.cancelJob(projectId, jobId);
  } catch (error) {
    rethrow(error, "Could not request cancellation.");
  }
});

export const bindImageStudioSession = withSession<
  BindSessionParameters,
  ProjectImageSession
>(async ({ projectId, eveSessionId, title }) => {
  try {
    return await imageStudioService.bindSession(projectId, eveSessionId, title);
  } catch (error) {
    rethrow(error, "Could not save the conversation.");
  }
});
