"use server";

import { revalidatePath } from "next/cache";

import { CoreApiRequestError } from "@/lib/clients/core.client";
import type {
  CreateProjectImageJobRequest,
  ProjectImageJob,
  ProjectImageSettings,
} from "@/lib/clients/generated/core/types.gen";
import { imageStudioService } from "@/lib/services/image-studio.service";
import {
  type AuthenticatedRequest,
  withSession,
} from "@/middleware/auth-middleware";

/**
 * Mutations for the image studio.
 *
 * Each one is a pass-through to Core, which owns every access check. The only
 * judgement here is turning a Core failure into a message a person can act on.
 */

interface StartGenerationParameters extends AuthenticatedRequest {
  projectId: string;
  /**
   * A catalog id, not an endpoint. Core maps it to the fal endpoint it has
   * verified and rejects anything else, so the browser never names a provider
   * URL of its own.
   */
  modelId: string | null;
  prompt: string;
  /**
   * Passed through whole. Spelling the fields out here meant every new
   * setting — `placementId` was the one that exposed it — had to be added in
   * three places and was silently dropped if it was not.
   */
  settings: ProjectImageSettings;
  parentAssetId: string | null;
  referenceAssetIds: string[];
  sessionId: string | null;
  /**
   * Generated by the client before the first attempt and reused on every
   * retry of the same intent, so a retry returns the original job rather than
   * buying a second image.
   */
  idempotencyKey: string;
}

/**
 * Why this one action returns a result instead of throwing.
 *
 * Next replaces a thrown server-action error with an opaque digest in
 * production, so a `kind` carried on the exception reaches the browser in
 * development and nowhere else. The bulk queue has to tell "the project is
 * already at its concurrency cap, hold this request" apart from "this request
 * will never work" — getting that wrong either drops images the person asked
 * for or retries a rejected one forever. So the outcome is data.
 */
export type StartGenerationResult =
  | { ok: true; job: ProjectImageJob }
  | { ok: false; kind: string | null; message: string };

interface CancelParameters extends AuthenticatedRequest {
  projectId: string;
  jobId: string;
}

function rethrow(error: unknown, fallback: string): never {
  if (error instanceof CoreApiRequestError) {
    throw new Error(error.message || fallback);
  }
  throw error instanceof Error ? error : new Error(fallback);
}

export const startImageGeneration = withSession<
  StartGenerationParameters,
  StartGenerationResult
>(async (input) => {
  try {
    const job = await imageStudioService.createJob(input.projectId, {
      ...(input.modelId
        ? { modelId: input.modelId as CreateProjectImageJobRequest["modelId"] }
        : {}),
      prompt: input.prompt,
      settings: input.settings,
      referenceAssetIds: input.referenceAssetIds,
      parentAssetId: input.parentAssetId,
      sessionId: input.sessionId,
      idempotencyKey: input.idempotencyKey,
    });
    revalidatePath(`/projects/${input.projectId}/studio`);
    return { ok: true, job };
  } catch (error) {
    if (error instanceof CoreApiRequestError) {
      return {
        ok: false,
        kind: error.kind ?? null,
        message: error.message || "Could not start the image generation.",
      };
    }
    throw error;
  }
});

export const requestImageJobCancel = withSession<
  CancelParameters,
  { accepted: boolean }
>(async ({ projectId, jobId }) => {
  try {
    return await imageStudioService.cancelJob(projectId, jobId);
  } catch (error) {
    rethrow(error, "Could not request cancellation.");
  }
});
