export enum JobActionErrorCode {
  // common
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  JOB_NOT_FOUND = "JOB_NOT_FOUND",

  // start job
  INVALID_INPUT = "INVALID_INPUT",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",

  // update job name
  UNAUTHORIZED = "UNAUTHORIZED",
}
