export enum StartJobErrorCodes {
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  INVALID_INPUT = "INVALID_INPUT",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
