import { OpenAPIHonoWithAuth } from "@/lib/hono";
import mountGetOrganizationBillingDetails from "./[id]/billing-details/get.js";
import mountGetOrganizationBillingPlan from "./[id]/billing-plan/get.js";
import mountApproveOrganizationCoworkerAccess from "./[id]/coworker-access/[accessId]/approve/post.js";
import mountDenyOrganizationCoworkerAccess from "./[id]/coworker-access/[accessId]/deny/post.js";
import mountRevokeOrganizationCoworkerAccess from "./[id]/coworker-access/[accessId]/revoke/post.js";
import mountGetOrganizationCoworkerAccess from "./[id]/coworker-access/get.js";
import mountGetOrganizationDeletion from "./[id]/deletion/get.js";
import mountGetOrganizationDesignMd from "./[id]/design-md/get.js";
import mountPutOrganizationDesignMd from "./[id]/design-md/put.js";
import mountGetOrganizationEnterpriseContractSummary from "./[id]/enterprise-contract-summary/get.js";
import mountCleanupOrganizationFiles from "./[id]/files/cleanup/post.js";
import mountPostOrganizationFiles from "./[id]/files/post.js";
import mountGetOrganization from "./[id]/get.js";
import mountGetOrganizationInvitations from "./[id]/invitations/get.js";
import mountRevokeOrganizationInviteLink from "./[id]/invite-links/[token]/delete.js";
import mountListOrganizationInviteLinks from "./[id]/invite-links/get.js";
import mountCreateOrganizationInviteLink from "./[id]/invite-links/post.js";
import mountDeleteOrganizationMemberSeat from "./[id]/members/[memberId]/seat/delete.js";
import mountPutOrganizationMemberSeat from "./[id]/members/[memberId]/seat/put.js";
import mountGetOrganizationMembers from "./[id]/members/get.js";
import mountGetOrganizationSeatSummary from "./[id]/seat-summary/get.js";
import mountGetOrganizationStripeCustomer from "./[id]/stripe-customer/get.js";
import mountPostOrganizationStripeCustomer from "./[id]/stripe-customer/post.js";
import mountGetOrganizationSubscription from "./[id]/subscription/get.js";
import mountPutOrganizationSubscriptionSeats from "./[id]/subscription/seats/put.js";
import mountApproveOrganizationVendorGrant from "./[id]/vendor-grants/[grantId]/approve/post.js";
import mountDenyOrganizationVendorGrant from "./[id]/vendor-grants/[grantId]/deny/post.js";
import mountRevokeOrganizationVendorGrant from "./[id]/vendor-grants/[grantId]/revoke/post.js";
import mountGetOrganizationVendorGrants from "./[id]/vendor-grants/get.js";
import mountPostOrganizationVendorGrants from "./[id]/vendor-grants/post.js";
import mountGetOrganizationBySlug from "./slug/[slug]/get.js";

const app = new OpenAPIHonoWithAuth();

// Mounted before the `/{id}` routes so the static `/slug` segment cannot be
// shadowed by the `{id}` path parameter.
mountGetOrganizationBySlug(app);
mountGetOrganization(app);
mountGetOrganizationDeletion(app);
mountGetOrganizationMembers(app);
mountPutOrganizationMemberSeat(app);
mountDeleteOrganizationMemberSeat(app);
mountGetOrganizationInvitations(app);
mountListOrganizationInviteLinks(app);
mountCreateOrganizationInviteLink(app);
mountRevokeOrganizationInviteLink(app);
mountGetOrganizationCoworkerAccess(app);
mountApproveOrganizationCoworkerAccess(app);
mountDenyOrganizationCoworkerAccess(app);
mountRevokeOrganizationCoworkerAccess(app);
mountGetOrganizationVendorGrants(app);
mountPostOrganizationVendorGrants(app);
mountApproveOrganizationVendorGrant(app);
mountDenyOrganizationVendorGrant(app);
mountRevokeOrganizationVendorGrant(app);
mountGetOrganizationSeatSummary(app);
mountGetOrganizationBillingPlan(app);
mountGetOrganizationEnterpriseContractSummary(app);
mountGetOrganizationStripeCustomer(app);
mountPostOrganizationStripeCustomer(app);
mountGetOrganizationBillingDetails(app);
mountGetOrganizationSubscription(app);
mountPutOrganizationSubscriptionSeats(app);
mountGetOrganizationDesignMd(app);
mountPutOrganizationDesignMd(app);
// Static `/{id}/files/cleanup` before `/{id}/files` is fine; both are exact paths.
mountCleanupOrganizationFiles(app);
mountPostOrganizationFiles(app);

export default app;
