import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { agentBranchName } from "./names.mjs";

const RC_BEGIN = "# >>> cloud-agent-db >>>";
const RC_END = "# <<< cloud-agent-db <<<";

/**
 * @param {string} repoRoot
 */
export function statePath(repoRoot) {
  return path.join(repoRoot, ".cursor", "cloud-agent-db.state.json");
}

/**
 * @param {string} repoRoot
 */
export function envFilePath(repoRoot) {
  return path.join(repoRoot, ".cursor", "cloud-agent-db.env");
}

/**
 * Machine-readable URLs for with-db.mjs (gitignored).
 * @param {string} repoRoot
 */
export function urlsFilePath(repoRoot) {
  return path.join(repoRoot, ".cursor", "cloud-agent-db.urls.json");
}

/**
 * @param {string} repoRoot
 */
export async function readState(repoRoot) {
  try {
    const raw = await readFile(statePath(repoRoot), "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * @param {string} repoRoot
 * @param {object} state
 */
export async function writeState(repoRoot, state) {
  const file = statePath(repoRoot);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, `${JSON.stringify(state, null, 2)}\n`, "utf8");
}

/**
 * @param {string} repoRoot
 */
export async function clearState(repoRoot) {
  const { unlink } = await import("node:fs/promises");
  for (const file of [
    statePath(repoRoot),
    envFilePath(repoRoot),
    urlsFilePath(repoRoot),
  ]) {
    try {
      await unlink(file);
    } catch {
      // ignore missing
    }
  }
}

/**
 * @param {string} repoRoot
 * @param {{ databaseUrl: string, databaseUrlUnpooled: string }} urls
 */
export async function writeEnvFile(repoRoot, urls) {
  const file = envFilePath(repoRoot);
  const urlsFile = urlsFilePath(repoRoot);
  await mkdir(path.dirname(file), { recursive: true });
  const body = [
    "# Generated by scripts/cloud-agent-db/provision.mjs — do not commit",
    `DATABASE_URL=${shellQuote(urls.databaseUrl)}`,
    `DATABASE_URL_UNPOOLED=${shellQuote(urls.databaseUrlUnpooled)}`,
    "",
  ].join("\n");
  await writeFile(file, body, "utf8");
  await writeFile(
    urlsFile,
    `${JSON.stringify(
      {
        DATABASE_URL: urls.databaseUrl,
        DATABASE_URL_UNPOOLED: urls.databaseUrlUnpooled,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
}

/**
 * @param {string} repoRoot
 * @returns {Promise<{ databaseUrl: string, databaseUrlUnpooled: string } | null>}
 */
export async function readUrlsFile(repoRoot) {
  try {
    const raw = await readFile(urlsFilePath(repoRoot), "utf8");
    const parsed = JSON.parse(raw);
    if (
      typeof parsed?.DATABASE_URL === "string" &&
      typeof parsed?.DATABASE_URL_UNPOOLED === "string"
    ) {
      return {
        databaseUrl: parsed.DATABASE_URL,
        databaseUrlUnpooled: parsed.DATABASE_URL_UNPOOLED,
      };
    }
  } catch {
    // missing or invalid
  }
  return null;
}

/**
 * @param {string} value
 */
function shellQuote(value) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/**
 * Inject source of cloud-agent-db.env into a shell rc file (idempotent).
 * @param {string} rcPath
 * @param {string} repoRoot
 */
export async function injectShellRc(rcPath, repoRoot) {
  const envPath = envFilePath(repoRoot);
  const block = [
    RC_BEGIN,
    `if [ -f ${shellQuote(envPath)} ]; then`,
    "  set -a",
    `  # shellcheck disable=SC1091`,
    `  . ${shellQuote(envPath)}`,
    "  set +a",
    "fi",
    RC_END,
    "",
  ].join("\n");

  let existing = "";
  try {
    existing = await readFile(rcPath, "utf8");
  } catch {
    existing = "";
  }

  const next = existing.includes(RC_BEGIN)
    ? existing.replace(
        new RegExp(
          `${escapeRegExp(RC_BEGIN)}[\\s\\S]*?${escapeRegExp(RC_END)}\\n?`,
        ),
        block,
      )
    : `${existing.trimEnd()}\n\n${block}`;

  await writeFile(rcPath, next, "utf8");
}

/**
 * @param {string} value
 */
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Patch DATABASE_URL / DATABASE_URL_UNPOOLED in app .env files.
 * @param {string} repoRoot
 * @param {{ databaseUrl: string, databaseUrlUnpooled: string }} urls
 */
export async function patchAppEnvFiles(repoRoot, urls) {
  const targets = [
    path.join(repoRoot, "apps", "core", ".env"),
    path.join(repoRoot, "apps", "web", ".env"),
  ];

  for (const file of targets) {
    let existing = "";
    try {
      existing = await readFile(file, "utf8");
    } catch {
      continue;
    }

    const next = upsertEnvLines(existing, {
      DATABASE_URL: urls.databaseUrl,
      DATABASE_URL_UNPOOLED: urls.databaseUrlUnpooled,
    });
    await writeFile(file, next, "utf8");
  }
}

/**
 * @param {string} contents
 * @param {Record<string, string>} values
 */
export function upsertEnvLines(contents, values) {
  const lines = contents.split("\n");
  const keys = new Set(Object.keys(values));
  const seen = new Set();
  const out = [];

  for (const line of lines) {
    const match = line.match(/^([A-Z0-9_]+)=/);
    if (match && keys.has(match[1])) {
      out.push(`${match[1]}=${values[match[1]]}`);
      seen.add(match[1]);
      continue;
    }
    out.push(line);
  }

  for (const key of keys) {
    if (!seen.has(key)) {
      if (out.length > 0 && out[out.length - 1] !== "") out.push("");
      out.push(`${key}=${values[key]}`);
    }
  }

  return `${out.join("\n").replace(/\n+$/, "\n")}`;
}

/**
 * Apply provisioned URLs into the current process (override).
 * @param {{ databaseUrl: string, databaseUrlUnpooled: string }} urls
 * @param {NodeJS.ProcessEnv} [env]
 */
export function applyUrlsToProcessEnv(urls, env = process.env) {
  env.DATABASE_URL = urls.databaseUrl;
  env.DATABASE_URL_UNPOOLED = urls.databaseUrlUnpooled;
}

/**
 * @param {string} agentId
 */
export function defaultStateForAgent(agentId) {
  return {
    agentId,
    branchName: agentBranchName(agentId),
  };
}
