/**
 * Regenerate `src/lib/image-studio/fal-catalog-snapshot.json`.
 *
 * The snapshot is the studio's cold-start catalog: it is what a fresh instance
 * serves before any provider call, and what it keeps serving if fal is
 * unreachable. It is committed on purpose, and it is regenerated by hand rather
 * than in CI because it is a capture of a third party's live state and a
 * reviewer should see what changed in it.
 *
 *   FAL_KEY=… pnpm --filter @sokosumi/core image-studio:refresh-catalog
 *
 * Roughly one call per endpoint plus a handful, paced and backed off, so it takes
 * a few minutes. It writes nothing unless the crawl produced models.
 */

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  fetchFalCatalogSources,
  normaliseFalCatalog,
} from "../src/lib/image-studio/fal-catalog-fetch.js";

const SNAPSHOT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "image-studio",
  "fal-catalog-snapshot.json",
);

async function main(): Promise<void> {
  const apiKey = process.env.FAL_KEY;
  if (!apiKey) {
    throw new Error("FAL_KEY is not set. The snapshot is a real capture.");
  }

  const sources = await fetchFalCatalogSources({
    fetchImpl: fetch,
    apiKey,
    onProgress: (message) => process.stderr.write(`${message}\n`),
  });
  const { models, exclusions } = normaliseFalCatalog(sources);
  if (models.length === 0) {
    throw new Error("The crawl produced no models; refusing to write.");
  }

  const snapshot = {
    // Read at import by `catalog.ts` and reported on the catalog route, so a
    // reader can always tell how old the cold-start catalog is.
    generatedAt: sources.fetchedAt.slice(0, 10),
    generatedAtExact: sources.fetchedAt,
    source:
      "GET https://api.fal.ai/v1/models?category=text-to-image&status=active, GET /v1/models/pricing, GET https://fal.ai/api/openapi/queue/openapi.json",
    endpointsListed: sources.models.length,
    modelsKept: models.length,
    // Kept in full rather than counted: every one of these is a model a person
    // might expect to see, and the reason it is missing should be reviewable
    // without re-running the crawl.
    exclusions: exclusions.sort((left, right) =>
      left.endpointId.localeCompare(right.endpointId),
    ),
    models: models.sort((left, right) => left.id.localeCompare(right.id)),
  };

  await writeFile(SNAPSHOT_PATH, `${JSON.stringify(snapshot, null, 2)}\n`);
  process.stderr.write(
    `wrote ${models.length} models (${exclusions.length} excluded) to ${SNAPSHOT_PATH}\n`,
  );
}

await main();
