import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { describe, expect, it, vi } from "vitest";
import type { TaskWithCoworker } from "@/app/tasks/types/task-board";
import {
  TaskStatus,
  type TaskTags,
  TaskVisibility,
} from "@/lib/clients/generated/core";
import { TaskCard } from "./task-card";
import { TaskTagSection } from "./task-tags";

const { navigateMock } = vi.hoisted(() => ({ navigateMock: vi.fn() }));
vi.mock("next-intl", () => ({
  useTranslations: () => (key: string) => key,
  useFormatter: () => ({ dateTime: (value: Date) => value.toISOString() }),
}));
vi.mock("@/lib/utils/datetime.client", () => ({
  useLocalizedDateTime: () => ({ formatShortDate: () => "Sep 26" }),
}));
vi.mock("./task-detail-link", () => ({
  TaskDetailLink: ({
    children,
    ...props
  }: {
    children: ReactNode;
    href: string;
    className?: string;
  }) => (
    <a
      {...props}
      onClick={(event) => {
        event.preventDefault();
        navigateMock();
      }}
    >
      {children}
    </a>
  ),
}));

const initialTags: TaskTags = {
  manual: ["design"],
  automatic: ["research"],
  rejected: [],
};

describe("TaskTagSection", () => {
  it("titles the section like the other sidebar headings, without a colon", () => {
    render(<TaskTagSection tags={initialTags} />);

    const heading = screen.getByRole("heading", {
      level: 2,
      name: "autoGeneratedTitle",
    });
    expect(heading).toHaveClass(
      "text-muted-foreground",
      "text-xs",
      "font-medium",
    );
  });

  it("shows automatic and legacy manual tags with no edit affordance", () => {
    render(<TaskTagSection tags={initialTags} />);
    expect(screen.getByText("autoGeneratedTitle")).toBeInTheDocument();
    // Legacy manual choices still lead and are still labelled as the user's.
    expect(screen.getByText("vocabulary.design")).toHaveAttribute(
      "title",
      "manual",
    );
    expect(screen.getByText("vocabulary.research")).toHaveAttribute(
      "title",
      "automatic",
    );
    expect(screen.queryByRole("button")).not.toBeInTheDocument();
    expect(screen.queryByRole("checkbox")).not.toBeInTheDocument();
    expect(screen.queryByRole("textbox")).not.toBeInTheDocument();
  });

  it("says so when a task has no tags yet", () => {
    render(<TaskTagSection />);
    expect(screen.getByText("empty")).toBeInTheDocument();
    expect(screen.queryByRole("button")).not.toBeInTheDocument();
  });
});

it("opens card tag overflow without following the task link", async () => {
  const task: TaskWithCoworker = {
    id: "task-1",
    name: "Review findings",
    status: TaskStatus.READY,
    visibility: TaskVisibility.PUBLIC,
    description: null,
    descriptionPlain: null,
    ownerId: "user-1",
    owner: { id: "user-1", name: "Owner", image: null },
    project: null,
    assignee: null,
    participants: [],
    commentsCount: 0,
    createdAt: "2026-09-26T00:00:00.000Z",
    updatedAt: "2026-09-26T00:00:00.000Z",
    jobsCount: 0,
    columnId: "todo",
    events: [],
    agents: [],
    tags: {
      manual: ["design"],
      automatic: ["research", "writing"],
      rejected: [],
    },
  };
  render(<TaskCard task={task} />);
  const user = userEvent.setup();
  const overflow = screen.getByRole("button", { name: "showAll" });
  expect(overflow.closest("a")).toBeNull();
  await user.click(overflow);
  const dialog = await screen.findByRole("dialog", { name: "label" });
  expect(within(dialog).getByText("vocabulary.writing")).toBeInTheDocument();
  expect(within(dialog).getByText("vocabulary.design")).toBeInTheDocument();
  expect(navigateMock).not.toHaveBeenCalled();
  await user.keyboard("{Escape}");
  await user.click(screen.getByRole("link", { name: task.name }));
  expect(navigateMock).toHaveBeenCalledTimes(1);
});
