"use client";

import { useTranslations } from "next-intl";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import type { TaskTags as TaskTagsDto } from "@/lib/clients/generated/core";

export function TaskTags({
  tags,
  compact = false,
}: {
  tags?: TaskTagsDto;
  compact?: boolean;
}) {
  const t = useTranslations("App.Tasks.Tags");
  const ids = [...(tags?.manual ?? []), ...(tags?.automatic ?? [])];
  const visible = ids.slice(0, compact ? 1 : 2);
  const remaining = ids.length - visible.length;
  if (!ids.length)
    return <p className="text-muted-foreground text-xs">{t("empty")}</p>;
  return (
    <div
      className="flex min-w-0 flex-wrap items-center gap-1"
      aria-label={t("label")}
    >
      {visible.map((id) => (
        <Badge
          key={id}
          variant="outline"
          className="text-muted-foreground rounded-sm font-normal"
        >
          {t(`vocabulary.${id}`)}
        </Badge>
      ))}
      {remaining > 0 ? (
        <Popover>
          <PopoverTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="relative z-10 min-h-6 px-1.5 text-xs"
              aria-label={t("showAll", { count: ids.length })}
              onPointerDown={(event) => event.stopPropagation()}
              onKeyDown={(event) => event.stopPropagation()}
            >
              +{remaining}
            </Button>
          </PopoverTrigger>
          <PopoverContent
            aria-label={t("label")}
            className="w-64 space-y-2"
            onPointerDown={(event) => event.stopPropagation()}
          >
            <p className="text-sm font-medium">{t("label")}</p>
            <div className="flex flex-wrap gap-1">
              {ids.map((id) => (
                <Badge key={id} variant="outline">
                  {t(`vocabulary.${id}`)}
                </Badge>
              ))}
            </div>
          </PopoverContent>
        </Popover>
      ) : null}
    </div>
  );
}

/**
 * Read-only. Tags are classified automatically; there is no correction UI. Rows a
 * user corrected while the editor existed still show those choices first, because
 * `mapTaskTags` keeps preferring the stored manual list over the automatic one.
 */
export function TaskTagSection({ tags }: { tags?: TaskTagsDto }) {
  const t = useTranslations("App.Tasks.Tags");
  const ids = [...(tags?.manual ?? []), ...(tags?.automatic ?? [])];
  return (
    <section className="space-y-2">
      <h2 className="text-muted-foreground text-xs font-medium">
        {t("autoGenerated")}
      </h2>
      <div className="flex flex-wrap gap-1">
        {ids.length ? (
          ids.map((id) => (
            <Badge
              key={id}
              variant="outline"
              title={t(tags?.manual.includes(id) ? "manual" : "automatic")}
            >
              {t(`vocabulary.${id}`)}
            </Badge>
          ))
        ) : (
          <p className="text-muted-foreground text-xs">{t("empty")}</p>
        )}
      </div>
    </section>
  );
}
