"use client";

import { useTranslations } from "next-intl";
import { Badge } from "@/components/ui/badge";
import type { TaskTagId } from "@/lib/clients/generated/core";

interface TaskDraftTagsProps {
  tags: TaskTagId[];
  status: "loading" | null;
}

/**
 * Read-only. Tags are classified automatically and are never edited by hand, so
 * this shows what was found and, while a request is out, that something is coming.
 * With neither it renders nothing rather than an empty row.
 */
export function TaskDraftTags({ tags, status }: TaskDraftTagsProps) {
  const t = useTranslations("App.Tasks.Tags");
  if (!tags.length && !status) return null;
  return (
    <section aria-label={t("autoGenerated")} className="space-y-2">
      <div className="flex flex-wrap items-center gap-2">
        <h2 className="text-muted-foreground text-xs font-medium">
          {t("autoGenerated")}
        </h2>
        {tags.map((tag) => (
          <Badge
            key={tag}
            variant="outline"
            className="text-muted-foreground rounded-sm font-normal"
          >
            {t(`vocabulary.${tag}`)}
          </Badge>
        ))}
        {!tags.length && status === "loading" ? (
          <p role="status" className="text-muted-foreground text-xs">
            {t("suggesting")}
          </p>
        ) : null}
      </div>
    </section>
  );
}
