name: Linting
on:
  pull_request:

env:
  DATABASE_URL: "postgresql://user:password@localhost:5432/sokosumi"

jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Biome checks
        run: pnpm check

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup
        with:
          turbo_team: ${{ vars.TURBO_TEAM }}

      - name: Run TypeScript typecheck
        run: pnpm typecheck
