name: ReviewDog
on: 
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Save Code Linting Report JSON
        run: pnpm run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: "lint_report.json"